# Generated by Django 3.2.7 on 2021-09-23 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appliances', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Slider',
            new_name='Appliances',
        ),
    ]
