# Generated by Django 3.2.7 on 2021-09-24 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appliances', '0003_rename_appliances_appliance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliance',
            name='brief',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='color',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='image',
            field=models.ImageField(upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='image1',
            field=models.ImageField(upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='image2',
            field=models.ImageField(upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='image3',
            field=models.ImageField(upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='image4',
            field=models.ImageField(upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='is_published',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='itemName',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='list_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='maker',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='price',
            field=models.CharField(max_length=20),
        ),
    ]
