# Generated by Django 3.2.7 on 2021-09-24 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Automobiles', '0002_rename_slider_automobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobile',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
